apiVersion: cert-manager.io/v1alpha2
kind: {{ .Values.kind }}
metadata:
  name: {{ .Values.name }}
spec:
  acme:
    server: {{ .Values.server }}
    # Email address used for ACME registration
    email: {{ .Values.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.secretName }}
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux